# Generated by Django 4.1.3 on 2022-11-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='is_vegan',
            field=models.BooleanField(default=False),
        ),
    ]
